# Site
name: 'Netverify'
description: 'Netverify is a site dedicated to expert commentary on network verification.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://netverify.github.io/'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    ratul:
      name:           Ratul Mahajan
      site:           https://ratul.org/
      avatar:         /assets/images/ratul-mahajan.jpg
      bio:            "Ratul Mahajan is an Associate Professor at the University of Washington (Paul G. Allen School of Computer Science) and a Co-founder and CEO of Intentionet, a company that is enabling safe, rapid evolution of computer networks using formal analysis and high-level design approaches. Prior to that, he was a Principal Researcher at Microsoft Research. He got his PhD at the University of Washington and B.Tech at Indian Institute of Technology, Delhi, both in Computer Science and Engineering."
      twitter:        ratulm

    beckett:
      name:           Ryan Beckett
      site:           http://beckett.ninja
      avatar:         /assets/images/ryan-beckett.jpg
      bio:            "Ryan Beckett is a Computer Scientist in the Mobility and Networking research group at Microsoft. He holds a PhD from Princeton in Computer Science as well as a B.S. in Computer Science and a B.A. in Mathematics from the University of Virginia."

    todd:
      name:           Todd Millstein
      site:           http://web.cs.ucla.edu/~todd/
      avatar:         /assets/images/todd-millstein.jpg
      bio:            "Todd Millstein is a Professor of Computer Science at UCLA, as well as a Co-founder and Chief Scientist at Intentionet.  He has also been an Academic Visitor at Oxford University, a Visiting Researcher at Microsoft Research, and a Visiting Fellow at Princeton University.  Todd received a Ph.D. from the University of Washington and an A.B. from Brown University, both in Computer Science."

    lvanbever:
      name:           Laurent Vanbever
      site:           https://nsg.ee.ethz.ch/people/laurent-vanbever/
      avatar:         /assets/images/laurent-vanbever.png
      bio:            "Laurent Vanbever is an Associate Professor at ETH Zurich. Prior to that, Laurent was a Postdoctoral Research Associate at Princeton University where he worked with Jennifer Rexford. He obtained his PhD degree in Computer Science from the University of Louvain in 2012. Prior to his PhD, Laurent earned a Master degree in Computer Science from the University of Louvain and a Master degree in Business Management from the Solvay Brussels School of Economics and Management, in 2008 and 2010, respectively."

    george:
      name:           George Varghese
      site:           http://web.cs.ucla.edu/~varghese/
      avatar:         /assets/images/george-varghese.jpg
      bio:            "George Varghese is a Chancellor's Professor of Computer Science at UCLA. He received his Ph.D. in 1992 from MIT after working at DEC designing DECNET protocols and products, including the bridge architecture and Gigaswitch. From 1993-1999, he was a professor at Washington University, and at UCSD from 1999 to 2013. He was the Distinguished Visitor in the computer science department at Stanford University from 2010-2011. From 2012-2016, he was a Principal Researcher and Partner at Microsoft Research working on network verification."

    david:
      name:           David Walker
      site:           https://www.cs.princeton.edu/~dpw/
      avatar:         /assets/images/david-walker.png
      bio:            "David Walker is a Professor of Computer Science at Princeton University. He received his doctoral and master’s degrees in computer science from Cornell, and his bachelor’s from Queen’s University in Kingston, Ontario.  During sabbaticals from Princeton, he has served as a visiting researcher at Microsoft Research in Redmond (2008) and in Cambridge (2009), and as Associate Visiting Faculty at the University of Pennsylvania (2015-2016)."

    gupta:
      name:           Aarti Gupta
      site:           https://www.cs.princeton.edu/~aartig/
      avatar:         /assets/images/aarti-gupta.jpg
      bio:            "Aarti Gupta is a Professor of Computer Science at Princeton University. Before joining the department, she worked at NEC Labs America where she led a team in investigating new techniques for formal verification of software and hardware systems, contributing both to their foundations and to successful industrial deployment. Professor Gupta received her Ph.D. in computer science from Carnegie Mellon University in 1994 after earning a master’s degree in computer engineering from Rensselaer Polytechnic Institute and a bachelor’s in electrical engineering from the Indian Institute of Technology in New Delhi."

    giannarakis:
      name:           Nick Giannarakis
      site:           https://www.nickgian.github.io
      avatar:         /assets/images/nick-giannarakis.jpeg
      bio:            "Nick is a PhD candidate at Princeton University, where he is currently advised by Prof. David Walker. He received a master's degree in Computer Science from ENS Cachan, and a diploma of Electrical and Computer Engineering from National Technical University of Athens."
      twitter:        naig_kcin

    loehr:
      name:           Devon Loehr
      site:           https://dkloehr.github.io
      avatar:         /assets/images/devon-loehr.jpg
      bio:            "Devon is a PhD candidate at Princeton University, where he is currently advised by Prof. David Walker. Devon graduated from Swarthmore College in 2018 with High Honors, with majors in Mathematics and Computer Science."

    thijm:
      name:           Tim Alberdingk Thijm
      site:           https://www.cs.princeton.edu/~tthijm/
      avatar:         /assets/images/tim-thijm.jpg
      bio:            "Tim is a PhD candidate at Princeton University, where he is currently advised by Prof. Aarti Gupta. Tim completed his BSc at the University of Toronto in 2018 in Computer Science and English."

    schmid:
      name:           Stefan Schmid
      site:           https://www.univie.ac.at/ct/stefan/
      avatar:         /assets/images/schmid.jpg
      bio:            "Stefan Schmid is a Full Professor at the University of Vienna, Austria. MSc and PhD at ETH Zurich, Postdoc at TU Munich and University of Paderborn, Senior Research Scientist at T-Labs in Berlin, and Associate Professor at Aalborg University, Denmark. Stefan Schmid is interested in the fundamental and algorithmic problems underlying networked systems. He received the IEEE Communications Society ITC Early Career Award 2016 and an ERC Consolidator Grant 2019.
"

    srba:
      name:           Jiri Srba
      site:           http://people.cs.aau.dk/~srba/
      avatar:         /assets/images/srba.jpg
      bio:            "Jiri Srba is a Full Professor in computer science at Aalborg University, Denmark. He holds MSc from Faculty of Informatics, Masaryk University in Brno and PhD degree from Aarhus University. Since 2005, he has been employed at Aalborg University. Jiri Srba is interested in applying formal methods such as model checking into industrial cases from computer networking, supervisory control and wireless adhoc networks.
"

    akella:
        name:       Aditya Akella
        site:       http://pages.cs.wisc.edu/~akella/
        avatar:     /assets/images/aditya-akella.jpg
        bio:        "Aditya Akella is a Professor of Computer Sciences at the University of Wisconsin-Madison, where he leads the Wisconsin Internet and Systems Research (WISR) Lab, and a Visiting Scientist at Google. Aditya has also been a Visiting Researcher at Microsoft (2014), a Visiting Associate Professor at the University of Washington (2013), and a Postdoc at Stanford University (2005-2006). Aditya has received numerous awards, including a Finalist for the Blavatnik National Award for Young Scientists (2020), an H.I. Romnes Faculty Fellowship (2018), SACM Student Choice Professor of the Year (COW) Award (2017, 2019), the Internet Engineering Task Force (IETF) Applied Networking Research Prize (2015), and the ACM SIGCOMM Rising Star Award (2014). Aditya received a Ph.D. in Computer Science from Carnegie Mellon University (2005) and a B.Tech. in Computer Science from Indian Insitute of Technology, Madras (2000)."

    gemberjacobson:
        name:       Aaron Gember-Jacobson
        site:       https://aaron.gember-jacobson.com
        avatar:     /assets/images/aaron-gember-jacobson.jpg
        bio:        "Aaron Gember-Jacobson is an Assistant Professor of Computer Science at Colgate University. Aaron's research focuses on network configuration verification and synthesis. Aaron enjoys teaching Introduction to Computing, Operating Systems, Computer Networks, and a First Year Seminar entitled 'The Unreliable Internet.' Aaron received a Ph.D. and Master of Science in Computer Science from the University of Wisconsin-Madison and a Bachelor of Science in Computer Science from Marquette University. During his Ph.D., Aaron was awarded the Internet Engineering Task force (IETF) Applied Networking Research Prize (2015) and an IBM Ph.D. Fellowship."

    jrex:
        name:       Jennifer Rexford
        site:       https://www.cs.princeton.edu/~jrex/
        avatar:     /assets/images/jennifer-rexford.jpg
        bio:        "Jennifer Rexford is the Gordon Y.S. Wu Professor of Engineering and the Chair of Computer Science at Princeton University. Before joining Princeton in 2005, she worked for eight years at AT&T Labs--Research. Jennifer received her BSE degree in electrical engineering from Princeton University in 1991, and her PhD degree in electrical engineering and computer science from the University of Michigan in 1996. Jennifer received the ACM SIGCOMM award for lifetime contributions and the IEEE Internet Award."
        twitter:    jrexnet

    pamela:
        name:       Pamela Zave
        site:       http://pamelazave.com/
        avatar:     /assets/images/pamela-zave.jpg
        bio:        "Pamela Zave is a researcher in the Computer Science Department of Princeton University.  She received a PhD degree in computer sciences from the University of Wisconsin--Madison and an AB degree in English from Cornell University.  She spent 36 years in the research divisions of Bell Labs  and AT&T Labs, doing interdisciplinary work at the intersection of formal methods and network services.  Dr. Zave is an ACM Fellow, an AT&T Fellow, and the 2017 recipient of the IEEE Harlan D. Mills Award for the development of sound software-engineering theory and sustained, impactful applications to practice. In addition to her research publications, she holds 32 patents."

    harryliu:
        name:       Hongqiang Harry Liu
        site:       http://www.hongqiangliu.com/
        avatar:     /assets/images/harry-liu.png
        bio:        "Hongqiang Harry Liu is a Director of Research in Alibaba Cloud and Alibaba DAMO Acedamy. He holds a PhD from the Department of Computer Science at Yale University and a bachelor's degree and a master's degree from the Department of Electronic Engineering at Tsinghua University. Before joining Alibaba, he served as a senior researcher at Microsoft Research Redmond and was responsible for the R&D and implementation of key technologies related to stable, high-performance Azure networks. His research interests cover cloud data center networks, backbone networks, mobile network transmission technologies, 5G networks, and device-side computing. He has served as a reviewer of papers in SIGCOMM and NSDI conferences and has published nearly 20 papers accepted by SIGCOMM, NSDI, and SOSP conferences. In 2014, he won the SIGCOMM Doctoral Dissertation Award - Honorable Mention."

    bruce:
        name:       Bruce Davie
        site:       https://systemsapproach.substack.com/
        avatar:     /assets/images/bruce-davie.jpg
        bio:        "Bruce Davie is a computer scientist noted for his contributions to the field of networking. He recently co-founded Systems Approach, LLC, to develop open source computer science educational materials. He is a former VP and CTO for the Asia Pacific region at VMware. He joined VMware during the acquisition of Software Defined Networking (SDN) startup Nicira. Prior to that, he was a Fellow at Cisco Systems, leading a team of architects responsible for Multiprotocol Label Switching (MPLS). Davie has over 30 years of networking industry experience and has co-authored 17 RFCs. He was recognized as an ACM Fellow in 2009 and chaired ACM SIGCOMM from 2009 to 2013. He was also a visiting lecturer at the Massachusetts Institute of Technology for five years. Davie is the author of multiple books and the holder of more than 40 U.S. Patents."

    siva:
      name:          Siva Kesava Reddy Kakarla
      site:          https://sivak.dev/
      avatar:        /assets/images/siva-kakarla.JPG
      bio:           "Siva Kakarla is a senior researcher in the Networking research group at Microsoft. He received a Ph.D. in Computer Science from the University of California Los Angeles, advised by Todd Millstein and George Varghese. During his Ph.D., he received a SIGCOMM best student paper award, UCLA Graduate Dean’s Scholar Award, and was a Facebook Ph.D. fellowship finalist. Siva received his undergraduate degree in Computer Science and Engineering from IIT Kharagpur."
      twitter:       SivaKesavaRK

    nate:
      name:          Nate Foster
      site:          https://www.cs.cornell.edu/~jnfoster/
      avatar:        /assets/images/nate-foster.jpg
      bio:           "Nate Foster is a Professor of Computer Science at Cornell University and a Platform Architect at Intel. The goal of his research is to develop languages and tools that make it easy for programmers to build secure and reliable systems. His current work focuses on the design and implementation of languages for programming software-defined networks. In the past he has also worked on bidirectional languages (also known as “lenses”), database query languages, data provenance, type systems, mechanized proof, and formal semantics. He received a PhD in Computer Science from the University of Pennsylvania, an MPhil in History and Philosophy of Science from Cambridge University, and a BA in Computer Science from Williams College. His awards include a Sloan Research Fellowship, an NSF CAREER Award, the SIGCOMM Rising Star Award, a Most Influential POPL Paper Award, a most Influential ICFP Paper Award, a Tien ‘72 Teaching Award, several Google Research Awards, a Yahoo! Academic Career Enhancement Award, a Cornell Engineering Research Excellence Award, and the Morris and Dorothy Rubinoff Award."
      twitter:       natefoster

    arvind:
      name:          Arvind Krishnamurthy
      site:          https://www.cs.washington.edu/people/faculty/arvind
      avatar:        /assets/images/arvind-krishnamurthy.jpg
      bio:           "Arvind Krishnamurthy is the Short-Dooley Professor in the Paul G. Allen School of Computer Science & Engineering. His research interests are in building effective and robust computer systems in the context of both data centers and Internet-scale systems. More recently, his research has focussed on programmable networks and systems for machine learning. He is an ACM fellow, a past program chair of ACM SIGCOMM and Usenix NSDI, is the Vice President of Usenix, and serves on the ICSI and CRA boards."
      twitter:       arvind_uw

    anduo:
      name:          Anduo Wang
      site:          https://anduowang.github.io/
      avatar:        /assets/images/anduo-wang.jpeg
      bio:           "Anduo Wang is an Associate Professor at Temple University, where she specializes in improving network state management using formal methods, databases, knowledge representation and reasoning, and logic programming. She received her Ph.D. from UPenn in 2013 and was a postdoctoral researcher at UIUC with Matthew Caesar and Brighten Godfrey before joining Temple University in 2016. Anduo has been the recipient of three NSF grants as a single-PI investigator, including the CRII in 2017, CNS core small in 2019, and CAREER in 2022. She has served in various networking venues, including as the General Chair for the ACM SOSR conference in 2020 and as a member of the ACM SIGCOMM Executive Committee as the SIGCOMM Information Services Director from 2017 to 2021."


# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
