# Site
name: 'Netverify'
description: 'Netverify is a site dedicated to expert commentary on network verification.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
url: 'https://netverify.github.io/'
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    ratul:
      name:           Ratul Mahajan
      site:           https://ratul.org/
      avatar:         /assets/images/ratul-mahajan.jpg
      bio:            "Ratul Mahajan is an Associate Professor at the University of Washington (Paul G. Allen School of Computer Science) and a Co-founder and CEO of Intentionet, a company that is enabling safe, rapid evolution of computer networks using formal analysis and high-level design approaches. Prior to that, he was a Principal Researcher at Microsoft Research. He got his PhD at the University of Washington and B.Tech at Indian Institute of Technology, Delhi, both in Computer Science and Engineering."
      twitter:        ratulm

    beckett:
      name:           Ryan Beckett
      site:           http://beckett.ninja
      avatar:         /assets/images/ryan-beckett.jpg
      bio:            "Ryan Beckett is a Computer Scientist in the Mobility and Networking research group at Microsoft. He holds a PhD from Princeton in Computer Science as well as a B.S. in Computer Science and a B.A. in Mathematics from the University of Virginia."
 
    todd:
      name:           Todd Millstein
      site:           http://web.cs.ucla.edu/~todd/
      avatar:         /assets/images/todd-millstein.jpg
      bio:            "Todd Millstein is a Professor of Computer Science at UCLA, as well as a Co-founder and Chief Scientist at Intentionet.  He has also been an Academic Visitor at Oxford University, a Visiting Researcher at Microsoft Research, and a Visiting Fellow at Princeton University.  Todd received a Ph.D. from the University of Washington and an A.B. from Brown University, both in Computer Science."

    lvanbever:
      name:           Laurent Vanbever
      site:           https://nsg.ee.ethz.ch/people/laurent-vanbever/
      avatar:         /assets/images/laurent-vanbever.png
      bio:            "Laurent Vanbever is an Associate Professor at ETH Zurich. Prior to that, Laurent was a Postdoctoral Research Associate at Princeton University where he worked with Jennifer Rexford. He obtained his PhD degree in Computer Science from the University of Louvain in 2012. Prior to his PhD, Laurent earned a Master degree in Computer Science from the University of Louvain and a Master degree in Business Management from the Solvay Brussels School of Economics and Management, in 2008 and 2010, respectively."
    
    george:
      name:           George Varghese
      site:           http://web.cs.ucla.edu/~varghese/
      avatar:         /assets/images/george-varghese.jpg
      bio:            "George Varghese is a Chancellor's Professor of Computer Science at UCLA. He received his Ph.D. in 1992 from MIT after working at DEC designing DECNET protocols and products, including the bridge architecture and Gigaswitch. From 1993-1999, he was a professor at Washington University, and at UCSD from 1999 to 2013. He was the Distinguished Visitor in the computer science department at Stanford University from 2010-2011. From 2012-2016, he was a Principal Researcher and Partner at Microsoft Research working on network verification."

    david:
      name:           David Walker
      site:           https://www.cs.princeton.edu/~dpw/
      avatar:         /assets/images/david-walker.png
      bio:            "David Walker is a Professor of Computer Science at Princeton University. He received his doctoral and master’s degrees in computer science from Cornell, and his bachelor’s from Queen’s University in Kingston, Ontario.  During sabbaticals from Princeton, he has served as a visiting researcher at Microsoft Research in Redmond (2008) and in Cambridge (2009), and as Associate Visiting Faculty at the University of Pennsylvania (2015-2016)."

    gupta:
      name:           Aarti Gupta
      site:           https://www.cs.princeton.edu/~aartig/
      avatar:         /assets/images/aarti-gupta.jpg
      bio:            "Aarti Gupta is a Professor of Computer Science at Princeton University. Before joining the department, she worked at NEC Labs America where she led a team in investigating new techniques for formal verification of software and hardware systems, contributing both to their foundations and to successful industrial deployment. Professor Gupta received her Ph.D. in computer science from Carnegie Mellon University in 1994 after earning a master’s degree in computer engineering from Rensselaer Polytechnic Institute and a bachelor’s in electrical engineering from the Indian Institute of Technology in New Delhi."

    giannarakis:
      name:           Nick Giannarakis
      site:           https://www.nickgian.github.io
      avatar:         /assets/images/nick-giannarakis.jpeg
      bio:            "Nick is a PhD candidate at Princeton University, where he is currently advised by Prof. David Walker. He received a master's degree in Computer Science from ENS Cachan, and a diploma of Electrical and Computer Engineering from National Technical University of Athens."
      twitter:        naig_kcin

    loehr:
      name:           Devon Loehr
      site:           https://dkloehr.github.io
      avatar:         /assets/images/devon-loehr.jpg
      bio:            "Devon is a PhD candidate at Princeton University, where he is currently advised by Prof. David Walker. Devon graduated from Swarthmore College in 2018 with High Honors, with majors in Mathematics and Computer Science."
      
    thijm:
      name:           Tim Alberdingk Thijm
      site:           https://www.cs.princeton.edu/~tthijm/
      avatar:         /assets/images/tim-thijm.jpg
      bio:            "Tim is a PhD candidate at Princeton University, where he is currently advised by Prof. Aarti Gupta. Tim completed his BSc at the University of Toronto in 2018 in Computer Science and English."

    schmid:
      name:           Stefan Schmid
      site:           https://www.univie.ac.at/ct/stefan/
      avatar:         /assets/images/schmid.jpg
      bio:            "Stefan Schmid is a Full Professor at the University of Vienna, Austria. MSc and PhD at ETH Zurich, Postdoc at TU Munich and University of Paderborn, Senior Research Scientist at T-Labs in Berlin, and Associate Professor at Aalborg University, Denmark. Stefan Schmid is interested in the fundamental and algorithmic problems underlying networked systems. He received the IEEE Communications Society ITC Early Career Award 2016 and an ERC Consolidator Grant 2019.
"

    srba:
      name:           Jiri Srba
      site:           http://people.cs.aau.dk/~srba/
      avatar:         /assets/images/srba.jpg
      bio:            "Jiri Srba is a Full Professor in computer science at Aalborg University, Denmark. He holds MSc from Faculty of Informatics, Masaryk University in Brno and PhD degree from Aarhus University. Since 2005, he has been employed at Aalborg University. Jiri Srba is interested in applying formal methods such as model checking into industrial cases from computer networking, supervisory control and wireless adhoc networks.
"

    akella:
        name:       Aditya Akella
        site:       http://pages.cs.wisc.edu/~akella/
        avatar:     /assets/images/aditya-akella.jpg
        bio:        "Aditya Akella is a Professor of Computer Sciences at the University of Wisconsin-Madison, where he leads the Wisconsin Internet and Systems Research (WISR) Lab, and a Visiting Scientist at Google. Aditya has also been a Visiting Researcher at Microsoft (2014), a Visiting Associate Professor at the University of Washington (2013), and a Postdoc at Stanford University (2005-2006). Aditya has received numerous awards, including a Finalist for the Blavatnik National Award for Young Scientists (2020), an H.I. Romnes Faculty Fellowship (2018), SACM Student Choice Professor of the Year (COW) Award (2017, 2019), the Internet Engineering Task Force (IETF) Applied Networking Research Prize (2015), and the ACM SIGCOMM Rising Star Award (2014). Aditya received a Ph.D. in Computer Science from Carnegie Mellon University (2005) and a B.Tech. in Computer Science from Indian Insitute of Technology, Madras (2000)."

    gemberjacobson:
        name:       Aaron Gember-Jacobson
        site:       https://aaron.gember-jacobson.com
        avatar:     /assets/images/aaron-gember-jacobson.jpg
        bio:        "Aaron Gember-Jacobson is an Assistant Professor of Computer Science at Colgate University. Aaron's research focuses on network configuration verification and synthesis. Aaron enjoys teaching Introduction to Computing, Operating Systems, Computer Networks, and a First Year Seminar entitled 'The Unreliable Internet.' Aaron received a Ph.D. and Master of Science in Computer Science from the University of Wisconsin-Madison and a Bachelor of Science in Computer Science from Marquette University. During his Ph.D., Aaron was awarded the Internet Engineering Task force (IETF) Applied Networking Research Prize (2015) and an IBM Ph.D. Fellowship."

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
